export const CONVERTER = {
    SET_LIST_CURRENCY: 'CONVERTER@SET_LIST_CURRENCY',
    CALCULATE_EXCHANGE: 'CONVERTER@CALCULATE_EXCHANGE',
    SET_TOTAL: 'CONVERTER@SET_TOTAL',
    SET_ERROR: 'CONVERTER@SET_ERROR',
};
